name: Build and deploy Python app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/in-a-word-bot:latest \
        --build-arg API_TOKEN=${{ secrets.API_TOKEN }} \
        --build-arg WEBHOOK_ENABLED=${{ secrets.WEBHOOK_ENABLED }} \
        --build-arg WEBHOOK_HOST=${{ secrets.WEBHOOK_HOST }} \
        --build-arg WEBHOOK_PORT=${{ secrets.WEBHOOK_PORT }} \
        --build-arg WEBHOOK_PATH=${{ secrets.WEBHOOK_PATH }} \
        --build-arg WEBAPP_HOST=${{ secrets.WEBAPP_HOST }} \
        --build-arg WEBAPP_PORT=${{ secrets.WEBAPP_PORT }} \
        --build-arg DEV_LINK=${{ secrets.DEV_LINK }} \
        --build-arg REPO_LINK=${{ secrets.REPO_LINK }} --no-cache

        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/in-a-word-bot:latest
